import fs from 'node:fs';
const b='/Users/takahashinaoki/Documents/Codex/2026-09-23/azookey-web-playground/dist/';
const src=fs.readFileSync(b+'router.js','utf8'),model=JSON.parse(fs.readFileSync(b+'LocalLanguageModel.json'));
const variant=process.argv[2]??'phrase';
const extra = "const knownBoundary=J.has(jp)||particles.some(p=>jp.endsWith(p)&&(J.has(jp.slice(0,-p.length))||particles.some(p2=>jp.slice(0,-p.length).endsWith(p2)&&J.has(jp.slice(0,-p.length-p2.length))))); const crossesEnglish=[...compound].some(([s,ends])=>s>=start-jp.length&&s<start&&[...ends].some(e=>e-s>=4&&E.has(word.slice(s,e).toLowerCase())&&!J.has(word.slice(s,e).toLowerCase()))); if(!knownBoundary&&!crossesEnglish&&a.end<n&&jp.length>=6&&particles.some(p=>jp.endsWith(p)&&this.isRomaji(jp.slice(0,-p.length)))&&prob(jp,true)>=.995) evidence=Math.max(evidence,2.5); ";
let mod=src.replace('const uncertaintyPenalty=',extra+'const uncertaintyPenalty=');
const rs=[];for(const s of [src,mod]){const {Router}=await import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));rs.push(new Router(model));}
const labels=d=>d.spans.flatMap((s,i)=>Array.from(s.text,(_,p)=>!s.protected&&d.decisions.find(x=>x.index===i)?.japaneseStart!=null&&p>=d.decisions.find(x=>x.index===i).japaneseStart));
const fixtures=['accuracy-v2/fresh-evaluation.json','multiswitch-evaluation.json','release-holdout.json','accuracy-v3/fresh-evaluation.json','accuracy-v3/final-unseen.json','accuracy-v4/development.json','accuracy-v4/final-evaluation.json','accuracy-v5/fresh-evaluation.json','accuracy-v6/fresh-evaluation.json','accuracy-v6/final-evaluation.json'];
const result=[];
for(const f of fixtures){const cs=JSON.parse(fs.readFileSync('work/azooKey-Local/LocalModel/'+f)),ts=rs.map(()=>({exact:0,damage:0,reversals:0})),changes=[];for(const c of cs){const want=Array.from(c.raw,(_,i)=>c.japaneseRanges.some(([a,b])=>a<=i&&i<b)),ss=rs.map(r=>{let old=[],damage=0,reversals=0;for(let n=1;n<=c.raw.length;n++){const a=labels(r.classify(c.raw.slice(0,n)));if(old.some((v,i)=>v!==a[i]))reversals++;if(c.englishRanges.some(([x,y])=>y<=n&&a.slice(x,y).some(Boolean)))damage++;old=a;}return{exact:+(JSON.stringify(old)===JSON.stringify(want)),damage,reversals};});ss.forEach((s,i)=>{for(const k in s)ts[i][k]+=s[k]});if(JSON.stringify(ss[0])!==JSON.stringify(ss[1]))changes.push({raw:c.raw,stats:ss});}const row={f,stats:ts,changes};result.push(row);console.log(JSON.stringify(row));}
fs.writeFileSync('work/azooKey-Local/LocalModel/accuracy-v7/diagnosis/'+variant+'.json',JSON.stringify(result,null,2));
