import fs from 'node:fs';
const b='/Users/takahashinaoki/Documents/Codex/2026-09-23/azookey-web-playground/dist/';const src=fs.readFileSync(b+'router.js','utf8'),model=JSON.parse(fs.readFileSync(b+'LocalLanguageModel.json'));
let mod=src.replace('mixedSegments(word){','mixedSegments(word,englishPhrase=false){').replace('this.mixedSegments(span.text):null','this.mixedSegments(span.text,spans.length>=2&&spans.at(-1).protected&&chars(spans.at(-1).text).every(whitespace)&&this.english.has(spans.at(-2).text.toLowerCase())&&!this.ambiguous.has(spans.at(-2).text.toLowerCase())):null');
mod=mod.replace('const anchors=new Map();',`const strongTail=end=>{const s=word.slice(end);return englishPhrase&&s.length>=4&&prefixes(s,['no','ni','de','wo','ha','ga','to','mo','kara','made','shite','shita','shimas','sare','suru'])&&!E.has(s.toLowerCase())&&(this.isRomaji(s)||this.isRomajiPrefix(s))&&prob(s,true)>=.88;};const anchors=new Map();`);
mod=mod.replace('start>0&&prob(candidate)<.12&&suffixes(word.slice(0,start),particles)','((start>0&&prob(candidate)<.12&&suffixes(word.slice(0,start),particles))||(start===0&&strongTail(end+1)))');
mod=mod.replace('upper(a.text[0])&&E.has(a.text.toLowerCase())','E.has(a.text.toLowerCase())&&(upper(a.text[0])||(a.text.length>=4&&strongTail(a.end)))');
mod=mod.replace('upper(p.pieces[0]?.text[0])&&E.has(p.pieces[0].text.toLowerCase())','E.has(p.pieces[0]?.text.toLowerCase())&&(upper(p.pieces[0].text[0])||(p.pieces[0].text.length>=4&&strongTail(p.pieces[0].text.length)))');
// Boundary guard for a four-letter romaji word may now admit a leading lexical English word with explicit Japanese continuation.
mod=mod.replace('if(!boundary)continue;', 'if(!boundary&&!(start===0&&strongTail(a.end)))continue;');
fs.writeFileSync('work/azooKey-Local/LocalModel/accuracy-v8/candidate-router4.mjs',mod);
const rs=[];for(const s of [src,mod]){const {Router}=await import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));rs.push(new Router(model));}
const labels=d=>d.spans.flatMap((s,i)=>Array.from(s.text,(_,p)=>!s.protected&&d.decisions.find(x=>x.index===i)?.japaneseStart!=null&&p>=d.decisions.find(x=>x.index===i).japaneseStart));
const fixtures=['accuracy-v2/fresh-evaluation.json','multiswitch-evaluation.json','release-holdout.json','accuracy-v3/fresh-evaluation.json','accuracy-v3/final-unseen.json','accuracy-v4/development.json','accuracy-v4/final-evaluation.json','accuracy-v5/fresh-evaluation.json','accuracy-v6/fresh-evaluation.json','accuracy-v6/final-evaluation.json','accuracy-v7/final-evaluation-corrected.json'];
const result=[];
for(const f of fixtures){const cs=JSON.parse(fs.readFileSync('work/azooKey-Local/LocalModel/'+f)),ts=rs.map(()=>({exact:0,damage:0,reversals:0})),changes=[];for(const c of cs){const want=Array.from(c.raw,(_,i)=>c.japaneseRanges.some(([a,b])=>a<=i&&i<b)),ss=rs.map(r=>{let old=[],damage=0,reversals=0;for(let n=1;n<=c.raw.length;n++){const a=labels(r.classify(c.raw.slice(0,n)));if(old.some((v,i)=>v!==a[i]))reversals++;if(c.englishRanges.some(([x,y])=>y<=n&&a.slice(x,y).some(Boolean)))damage++;old=a;}return{exact:+(JSON.stringify(old)===JSON.stringify(want)),damage,reversals};});ss.forEach((s,i)=>{for(const k in s)ts[i][k]+=s[k]});if(JSON.stringify(ss[0])!==JSON.stringify(ss[1]))changes.push({raw:c.raw,stats:ss});}const row={f,stats:ts,changes};result.push(row);console.log(JSON.stringify(row));}
fs.writeFileSync('work/azooKey-Local/LocalModel/accuracy-v8/phrase-tail4.json',JSON.stringify(result,null,2));
